Repository fujiapple852/trippy, pull requests merged in 2022-05, with the labels that each got.

#84 Doc readme features
  README.md
Labels: documentation

#99 doc: add basic CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#104 Fix tearing
  src/backend.rs
  src/tracing/tracer.rs
Labels: bug

#109 fix: `largest_ttl` set incorrectly when `first-ttl` and `max-ttl` specified
  src/tracing/tracer.rs
Labels: bug

#114 doc: update status of `Windows` support and link to issue tracker
  README.md
Labels: documentation

#115 fix: incorrect conditional complication for `Windows` in `caps.rs`
  src/caps.rs
Labels: bug

#117 fix: `DisableMouseCapture` was being invoked without a prior `EnableMouseCapture`
  src/frontend.rs
Labels: bug, tui

#130 Limit nix features
  Cargo.lock
  Cargo.toml
Labels: build

#132 fix(tracer): incorrect handling of `DestinationUnreachable` packets for `udp` tracing
  src/tracing/tracer.rs
Labels: bug, udp

#136 doc: Use project README.md as documentation for the library crate on `docs.rs` (#128)
  src/lib.rs
Labels: documentation

#137 fix(dns): do not show `fqdn` for reverse DNS queries from `TrustDns` resolver
  src/dns.rs
Labels: bug, dns

#138 feat: show a better error message for a failed DNS lookup
  src/main.rs
Labels: enhancement, dns

#141 fix(docker): add README.md and LICENCE to docker image
  Dockerfile
Labels: bug, package

#146 build: build all dependencies as a separate Docker layer to speed up recompilation
  Dockerfile
Labels: build

#149 fix: filter for Ipv4 addresses when resolving hostnames
  src/main.rs
Labels: bug, dns

#150 chore: add #148 to CHANGELOG.md for `0.3.1` release
  CHANGELOG.md
Labels: chore

#160 fix(net): UDP checksum was not being set
  src/tracing/net.rs
Labels: bug, udp

#161 Feat use socket for udp tracing
  src/tracing/net.rs
Labels: enhancement, udp

#164 feat: added `source_address` cli option to specify the desired source IP address (#162)
  src/config.rs
  src/main.rs
  src/tracing/error.rs
  src/tracing/net.rs
Labels: enhancement, tcp, udp

#166 feat: rename cli flag `tui-max-addresses-per-hop` as `tui-max-addrs`
  src/config.rs
  src/main.rs
Labels: tui

#168 feat: added `--tos` (`-Q`) flag to set the `TOS` (aka `DSCP`+`ECN`) flag for `TCP` and `UDP` tracing
  src/config.rs
  src/main.rs
  src/tracing/net.rs
  src/tracing/types.rs
Labels: enhancement, tcp, udp

#169 chore: added gitter badge
  README.md
Labels: chore

#175 fix(net): after setting `set_reuse_port` on the TCP socket the check for `AddrInUse` and `AddrNotAvailable` has to moved from the `bind` to the `connect` call
  src/tracing/net.rs
Labels: bug, tcp

#181 feat(ui): add Ctrl-C as an alternative keyboard input to quit the app
  src/frontend.rs
Labels: enhancement, tui

#186 chore: update all dependencies to the latest semver compatible versions
  Cargo.lock
Labels: dependencies, chore

#187 chore: update MSRV to `1.60` to support `pnet` version `0.30.0`
  .github/workflows/ci.yml
Labels: chore

#188 fix(report): tracer failures not being shown for reports (#183)
  src/main.rs
  src/report.rs
Labels: bug, report

#190 fix(report): setting `--report-cycles` to `1` returns no traces (#189)
  src/backend.rs
  src/report.rs
Labels: bug, report
